sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: java-ai-lql
    region: cn-beijing
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    app-id: wx823d9908eabbf0e1
    secret: c9b15b8bf3f853ba926b5fd0ae1fcfd7

